
server:
  port: 8082
  
spring:
  application:
    name: user
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(vZSAzPqDeMa6QyAfOnjsGw==)
    password: ENC(vj6RHAkuT7UvXf5GiKKVdA==)
    url: ENC(xFYrS41Z+hZQUu5Ar4NLMs5FgIFehTtXzlh1zkLsgXK2QchvGpdUIbSYUUwJf1gmZ/gWTJRfepAIraNOqyaV3Z09gHwI/9bv1ZtSvQnqZw0g2kIpibaEiQ==)
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

  redis:
    port: 8080
    database: 0
    host: ENC(FVFRGTDT5QVSJbEfoGADCNCyZHNiTyOp)
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
    
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
      
  rabbitmq:
    host: ENC(Idi2U0s9o+Nirn1A3VPi9pWyvsTfWQXz)
    port: 5672
    username: ENC(4vwbGkk/yPNDZOk/areNuw==)
    password: ENC(TtZI4XvF651qurD25vbCF6NzrFHseOCn)  
    
mybatis:
  mapper-locations: classpath*:com/yzeng/userserver/mapper/**/*Mapper.xml
  type-aliases-package: com.yzeng.userserver.DO 

#设置全局请求路径前缀
#server:
#  servlet:
#    context-path: /user


#是否激活 swagger true or false
swagger:
  is:
    enable: true


